{% set version = "1.2022.2" %}

package:
  name: plantuml
  version: {{ version }}

source:
  url: https://github.com/plantuml/plantuml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5cc9d409e66b7ee61aff2b78de61c482d5cd149f8a64af9e9608c478a6366558

build:
  number: 0

requirements:
  build:
    - maven
    - graphviz <3
  run:
    - openjdk
    - graphviz <3

test:
  commands:
    - plantuml -version
    - plantuml -help

about:
  home: http://plantuml.com
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Generate UML diagram from textual description
  description: |
    PlantUML is a component that allows to quickly write:

      - Sequence diagram,
      - Use case diagram,
      - Class diagram,
      - Activity diagram,
      - Component diagram,
      - State diagram,
      - Object diagram,
      - Deployment diagram,
      - Timing diagram

    And also:

      - Activity diagram (legacy syntax)
      - Archimate diagram
      - Gantt charts
      - SALT UI mockups

    Furthermore:

      - Hyperlinks and tooltips
      - Creole: rich text, emoticons, unicode, icons
      - OpenIconic icons
      - Sprite icons
      - AsciiMath mathematical expressions

    To know more about PlantUML, please visit http://plantuml.com/

  dev_url: https://github.com/plantuml/plantuml

extra:
  recipe-maintainers:
    - bollwyvl
