{% set version = "1.2023.0" %}

package:
  name: plantuml
  version: {{ version }}

source:
  url: https://github.com/plantuml/plantuml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a74f5256fa07bcac3f0c3105b28562c3061bc5bb1d9d28925f83cf7b56a6a314

build:
  number: 0
  # TODO: restore after https://github.com/conda-forge/gradle-feedstock/pull/51
  skip: true  # [win]

requirements:
  build:
    - openjdk
    - gradle
    - graphviz
  run:
    - openjdk
    - graphviz

test:
  requires:
    - m2-grep  # [win]
  commands:
    - plantuml -version | grep -E {{ version.replace('.', '\.') }}
    - plantuml -help

about:
  home: http://plantuml.com
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Generate UML diagram from textual description
  description: |
    PlantUML is a component that allows to quickly write:

      - Sequence diagram,
      - Use case diagram,
      - Class diagram,
      - Activity diagram,
      - Component diagram,
      - State diagram,
      - Object diagram,
      - Deployment diagram,
      - Timing diagram

    And also:

      - Activity diagram (legacy syntax)
      - Archimate diagram
      - Gantt charts
      - SALT UI mockups

    Furthermore:

      - Hyperlinks and tooltips
      - Creole: rich text, emoticons, unicode, icons
      - OpenIconic icons
      - Sprite icons
      - AsciiMath mathematical expressions

    To know more about PlantUML, please visit http://plantuml.com/

  dev_url: https://github.com/plantuml/plantuml

extra:
  recipe-maintainers:
    - bollwyvl
